version: '3.8'

services:
  postgres:
    build: ./docker/postgresql
    volumes:
      - data_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "app"
    ports:
      - "54321:5432"

volumes:
  data_postgres:
    driver: local
